### ISSUE TITLE
Refactor a use of `head` to use pattern matching instead

### ISSUE THREAD

**Issue by dogweather** [dogweather/analyze-ors-amendment-haskell#2]
In `Main.hs`, [the first command line argument is retrieved](https://github.com/public-law/analyze-oregon-law-haskell/blob/master/analyze/src/Main.hs#L19-L23) like this:

```haskell
  args ← getArgs
  when (length args ≠ 1)
    (fail "Usage: analyze [filename]")

  let pdfFilename = head args
```

Let's refactor this for more safety and typical haskell style.

**Comment by astynax** [comment]
Can I rewrite current CLI using smth like `options-applicative`? New CLI also will close #1

**Comment by dogweather** [comment]
Please do! I'm very new to Haskell, and I'd like to see a more advanced approach. That library looks great. I didn't know about it.

**Comment by astynax** [comment]
Ok :)
