### ISSUE TITLE
Configure for Travis CI

### ISSUE THREAD

**Issue by dogweather** [dogweather/analyze-ors-amendment-haskell#5]
CI is enabled, but there's no `.travis.yml` file yet.

**Comment by ooade** [comment]
You have no test, so why do you need a CI?

**Comment by dogweather** [comment]
There are definitely tests - https://github.com/public-law/analyze-oregon-law-haskell/tree/master/analyze/test

I think I made everything a directory level too deep.

**Comment by ooade** [comment]
Oh! Okay. Didn't check it well :sweat_smile:
